alaoweb/2020.alaoweb.org

- _layouts/default.html
- _layouts/post.html
Updating to Bootstrap 4 doesn't appear to have any negative consequences that I can see.
> updated to bootstrap 4.5.0

- _data/team.yml
To test:
- build locally
- confirm that Zach Walton photo is on the team page
> ADD: zach walton to team with photo

- _config.yml
Confirm contact information is correct by visiting the /cod page.
Closes #4
> UPDATE: Contact info for code of conduct

- _sass/vendor/bootstrap/_modals.scss
To Test:
- Navigate to the `/schedules` page
- Click on a few sessions in the grid
- Ensure that the background fades and the session modal appears
Closes #27
> FIX: swap .in for class .show and update opacity for behavior changes

- _data/team.yml
still missing a few, but this is what I've got for now
> added pronouns for several team members

- _data/speakers.yml
PR closes #70 :
- Removes mid-sentence split of text in Nancy Kirkpatrick's bio
- Uses special character to handle multiline strings in YAML
- See: [Stackoverflow](https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-over-multiple-lines/21699210#21699210)😃
> Removes Mid-Sentence Split of Text in Kirkpatrick Bio

- _includes/poster.html
- _includes/posters.html
- _posts/2020-02-01-author-poster-title.markdown
- _posts/2020-06-23-gale-collaboration.md
* creates a new bogus poster
* replaces `presenter` string with `presenters` array in post/poster data
* modifies poster and posters layout to accommodate new data structure
* closes #77
> handle multiple-presenter posters

- _data/team.yml
* finishes adding pronouns for the team 
* addresses but still more work to do on #57
> finish team pronouns

- _includes/poster.html
- _includes/posters-modals.html
- _includes/posters.html
- _includes/schedule.html
- _includes/session-search.html
- _includes/sponsors.html
reformats html so it doesn't break long html tags into multiple lines
> Undo "prettier" html

- _config.yml
> pluralize Pre-Conferences in virtual conf block on front page

- _config.yml
Enables registration button in preparation for opening registration
Closes #124
> UPDATE: enable registration button

- _config.yml
> ADD: Google site verification code

- _config.yml
Adds GA property to site. That's it.
Closes #139
> ADD: Google Analytics property id

- _data/sessions.yml
Just adding in spaces for the presentations.
> Adding Presentations to sessions.yml

- _config.yml
- _includes/footer.html
- _includes/hero.html
- _includes/navigation.html
* added conference title and date to screen-reader friendly tags on the front page
* fixed a few places where links and images were missing titles/text to display
> Accessibility fixes

- _includes/tickets-2.html
> add conference dates to registration section

- _data/speakers.yml
- _includes/speakers-list-2.html
- _includes/speakers-list.html
To Test:
- View the `/speakers/` page of the site and ensure cards are listed in alphabetical order by surname
Closes #153
> Alphabetically Sort Speakers by Surname 

- _includes/posters-modals.html
> show only presenters for one poster in posters-modal

- _includes/sessions-modals.html
> display sessions sponsor on regular sessions

- _includes/modal-speaker-info.html
- _includes/posters-modals.html
- _includes/sessions-modals.html
* replaces vid with a link to the poster
* eliminates speaker list from top of posters modal
* adds poster speaker photo to bio
* uses single template for speaker photo/bio on both session and poster modals
* closes #167
> poster modal more like session modal, hide vid from modal

- _includes/speaker-div.html
Adds the gradient to darken the lower 25% of the speaker cards. To avoid abrupt contrast changes to each card, I've intentionally made this addition very subtle.
Closes #173
> UPDATE: adds top-to-bottom linear-gradient to speaker cards

- _data/sessions.yml
- _data/speakers.yml
This PR adds pronouns to `speakers.yml` and links id to `sessions.yml`
Closes #199
> Add Enimil Pronouns and Photo to Session in Schedule Grid

- _includes/posters.html
- _includes/top-section-posters.html
- _posts/2020-07-01-accessible-pdfs.md
- _sass/partials/_posters.scss
> Poster list

- _config.yml
I've commented out the link for the form to apply for a scholarship.
> Scholarship_application_deactivation

- _data/schedule.yml
> Moves All IG Sessions to Friday Lunch Hour

- _includes/posters.html
Closes #233 
* in _config.yml, set `showPosters: true` in line 195
* `bundle exec jekyll build`
* `bundle exec jekyll serve`
* check for alphabetical sort on: http://localhost:4000/posters/
> sorts posters alphabetically

- _data/sessions.yml
- _includes/sessions-modals.html
> Adds IG Meeting Links to sessions.yml

- _data/schedule.yml
- _data/sessions.yml
This PR adds an awards session to the schedule grid. I'll open a separate issue for the missing description.
Closes #241
> Add Awards Session to Schedule Grid

- _sass/partials/_zoe-effect.scss
> FIx: Display of Social Media Icons on Featured Speaker Cards

- _data/sessions.yml
> awards description

- _config.yml
- _includes/tickets-2.html
* change over to regular price tickets
* add logic to show past tense language when tickets no longer on sale
> update ticket offerings

- _data/sessions.yml
This PR updates the description and title of the new member session. Not too much to test, but feel free to check for typos :)
Closes #249
> Updates the Description and Title of the ALAO Membership Session

- _data/sessions.yml
> Update Preconference, Membership, and Awards Meetings

- _config.yml
- _data/sessions.yml
- _includes/sessions-modals.html
> Adds Support for Multiple Surveys

- base64.html
- js/base64-encoder.js
* the other half of #274 
* to ensure secrecy, #275 uses a JSON file with base64-encoded values to obfuscate the award winners in the repo
* this PR introduces an interface to convert a JSON file to one with base64-encoded values (it also has a "decode" option for confirmation purposes
* See: http://localhost:4000/tools/base64.html
* or: https://deploy-preview-276--alao-production.netlify.app/tools/base64.html
```
[
{
"description": "The Jay Ladd Distinguished Service Award recognizes an individual who has (1) been an Academic Library Association of Ohio member for at least 5 years (2) promoted academic libraries and librarianship on his or her own campus and within the state (3) provided sustained leadership in the promotion of Academic Library Association of Ohio, e.g., committee …
```
> Base64 encode json
