alaoweb/2020.alaoweb.org

_config.yml
preconference.html

This code adds a new boolean variable to `_config.yml` called `preconferenceLocationEnable`.
To test:
- Set `preconferenceLocationEnable` to `True`. Render site locally. Information for Nationwide Hotel and Conference Center should be shown on the preconference page .
- Set `preconferenceLocationEnable` to `False`. Render site locally. Location info should _not_ appear on the preconference page.
close #8

FIX: use a boolean to toggle display of physical location for preconf

---

_data/speakers.yml
_includes/speakers-modals.html

**Enhancement to render multiline strings in speaker bios using newlines**
To Test:
- Confirm 1 preconference and 2 keynote speakers are displaying in the 'Featured Speakers' section of the main conference site.
- Visit the `/Speakers` page, confirm that clicking on a speaker's image display's a modal with their bio information and any associated sessions. *Note* - session information might not be accurate at this stage.

UPDATE: keynote bios, speaker data, and speaker-modals

---

_config.yml
_layouts/default.html

This PR adds a variable for a Google Maps API key to `_config.yml` and updates the JavaScript API calls to use the new API key.
**Note:** As this API key has been published, the credentials are limited to only the Google Maps JavaScript API and the usable has been limited to HTTP Referrer of `2020.alaoweb.org/*`. As such, the maps will not display during local development, only on the published site. _Check the browser console for additional details during local development_
Closed #39

Fix 'Development Only' Google Maps Watermark

---

_config.yml
_data/schedule.yml
_data/sessions.yml
_posts/2020-02-01-author-poster-title.markdown
posters.html
preconference.html
schedule.html
speakers.html
team.html

This PR contains a set of minor updates to:
- universally use an abstract background in the top-section of each site page
- update the pre-conference description on the schedule
- update the schedule with most recent info
- disable physical location map for the pre-conference
- remove second pre-conference from schedule
We will likely modify some of these elements as time goes on, but I want to get the site into a reasonable - and slightly more cohesive - deployable state.

Set of Minor Updates for CPC Meeting

---

_config.yml

Submitting an email address to subscribe to the ALAO mailing list from the conference site will post the email address to the ALAO MailChimp audience. MailChimp will reply with a subscription confirmation message upon addition.
I've confirmed that MailChimp audiences can be exported as a `.csv`
Closes #19

Use MailChimp Audience to Capture Email Contacts

---

_config.yml
_includes/top-section-posters.html
_posts/2020-02-01-author-poster-title.markdown
_posts/2020-06-23-gale-collaboration.md
posters.html

To test:
- Update `postersBackground:` variable in `_config.yml` to another image file, e.g. `cod.png`
- Rebuild site. New image should display on:
- Main posters list `http://127.0.0.1:4000/posters/`
- Each individual posters
Closes #87

Adds postersBackground Variable to _config.yml

---

_posts/2020-02-01-author-poster-title.markdown
_posts/2020-06-23-gale-collaboration.md

added "published: false" to bogus poster sessions to remove them from displaying in the session search

unpublished bogus posters

---

_config.yml
preconference.html

* main menu
* in the image block on the front page
* in the page header & title for the preconf page
* closes #127 
https://2020-staging.alaoweb.org/preconference/

Pluralize preconference(s) in headers and menu

---

_includes/top-section-posters.html

Several weeks ago, it was decided to use a common SVG background for all posters and set that background value in `_config.yml` as `postersBackground: waves-background.svg`, rather than in each poster's front matter.
This PR ensures that the `enable-overlay` class is uniformly applied to each poster's template, by removing the logic that check for an `image: background.file` in each poster before applying the overlay.
Closes #134

FIX: stabilzes top-section SVG background

---

_data/speakers.yml
_includes/session-search.html
_posts/2020-07-01-alumni-engagement.md
_posts/2020-07-01-bracketology.md
_posts/2020-07-01-critical-info-lit.md
_posts/2020-07-01-digital-initiative-workflows.md
_posts/2020-07-01-diversity-dialogues.md
_posts/2020-07-01-hs-location.md
_posts/2020-07-01-info-lit-gen-ed.md
_posts/2020-07-01-libcal-to-circulate.md
_posts/2020-07-01-marketable-skills.md
_posts/2020-07-01-mindfulness.md
_posts/2020-07-01-mini-conference.md
_posts/2020-07-01-no-login-needed.md
_posts/2020-07-01-oa-consultancy-service.md
_posts/2020-07-01-pandemic-student-services.md
_posts/2020-07-01-safe-space.md
_posts/2020-07-01-social-justice.md
_posts/2020-07-01-sustainable-library-instruction.md
_posts/2020-07-01-transitioning-library-services.md
_posts/2020-07-01-work-from-home.md

Right now, the data structure in posts (posters) doesn't include a link to the speakers.yml file, so it doesn't have access to speaker images. This PR adds a backwardly compatible upgrade. We can add a `speaker-data` parameter to posts, e.g.: `speaker-data: [3,5,9]`. If speaker-data is used, it overrides the inline `presenters` parameter with content from the speakers.yml file. 
http://localhost:4000/session-search/
The data for Rob Withers' poster and the Ken Irwin/Alisa Mizikar/Kristen Peters poster are coming from the speakers.yml file; Ken/Alisa/Kristen have photos from that file; Rob doesn't because he currently hasn't sent one. 
If we go forward with this approach, we'll need to add the speaker-data to the other poster sessions

Add faces to poster list in session-search

---

_includes/speaker-div.html

After increase the `col-` value of the speaker figure captions, all presenter names fit without floating above the card baseline. Below is an 'after increase' example using `Pamela Espinosa de los Monteros`
Closes #179

UPDATE: increase col-md value in speaker figure caption

---

_includes/speaker-div.html

This PR truncates the display of a speaker's biography at 20 words on their card. At 20 words, an ellipsis is introduced. Clicking on the card will display the entire biography. Example below.
Closes #180

UPDATE: truncate biographies at 20 words

---

_data/schedule.yml
_data/sessions.yml
_includes/schedule.html

**To test:** confirm that the four (4) IG sessions on the schedule grid open modals with the interest group's discussion topic and button to launch a Zoom session.
We may need to enhance this PR (i.e. functionality) at a later time. For the moment, I want to ensure that we have something basic in place for this conference cycle.
Closes #177

Adds IG Breakfast and Lunch Sessions to Schedule Grid

---

_data/schedule.yml
_data/sessions.yml

This PR:
- Adds a new members session to the Wednesday evening slot on the conference schedule
Following up with Maureen for the exact description that needs to be included. Closes #193

Adds New Members Session to Schedule

---

_data/schedule.yml
_data/sessions.yml
_includes/sessions-modals.html

This PR:
- Adds Thursday Night Social to the schedule grid
- Teaches `sessions-modals.html` to identify the subtype of `social` and to not display sponsors for any sessions of this subtype
Closes #194

Adds Thursday Night Social to Schedule

---

_includes/session-search.html

Adds Nondescript Default Photo to Entries on Session Search Interface 

---

_includes/posters-modals.html

To Test:
- toggle the boolean `showPosters` in `config.yml`. When the value of showPosters is False, the 'View Poster' button should not display in the poster modals.
Closes #212

Adds Logic to Toggle the View Poster Button Based Upon showPosters in config.yml

---

_config.yml

This PR:
- Enables the display of the conference hashtag as a section on the main conference page.
To Test:
- Scroll until just above the registration section and you'll see the conference hashtag section.
Closes #226

Enable Conference Hashtag Section

---

_config.yml

This PR adds the session feedback survey URL and the value to capture the session title from the conference website and automatically update the Google Form response with the session title.
Closes #230

Updates 'Session Feedback' URL and Form Entry Values

---

_data/sessions.yml
_includes/sessions-modals.html

This PR adds some logic to only display the 'Session Feedback' button when `session.subtype` is `session`.
Closes #239

Display 'Session Feedback' Button on Sessions Only 

---

_data/schedule.yml
_data/sessions.yml

To Test:
- set `showSessions: true`
- confirm that staffed 'help desk' hours for each day are accurate
- confirm that modal button reads, "Launch Help Desk"
Closes #280

Add 'Help Desk' the Daily Schedule Grid

---

_includes/poster.html
_includes/sponsors-per-session.html
_posts/2020-07-01-bracketology.md

* adds support for "additional_support" option on posters
* adds Emery Pratt as additional_support in Bracketology poster
* closes #284 
* [Bracketology poster](http://localhost:4000/posters/bracketology) should show Emery Pratt logo under additional support in sponsor section
* Other posters (e.g. http://localhost:4000/posters/art-design ) should not show an additional support section

Poster additional support

---

_posts/2020-07-01-no-login-needed.md

one of the poster types available is "github" but it didn't get used on this poster; I update the metadata to gett the GH icon instead of a standard link icon

applied github icon to "no login needed" link
